alias cs='cd;ls'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias nmaper='nmaper.sh'
alias ls='ls --color=auto'
alias c='clear'
alias la='ls -la'
alias grep='grep --color=auto'
alias python3='python3 -B'
