alias cs='cd;ls'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias nmaper='nmaper.sh'
alias ls='ls --color=auto'
alias c='clear'
alias la='ls -la'
alias sublist3r='python3 ~/Tools/Sublist3r/sublist3r.py'
alias grep='grep --color=auto'

